--- 
- hosts: 172.30.0.11 
  become: yes 
  tasks: 
  - include_tasks: myfiles.yml 
  - name: creare a folder 
    file: 
     path: /home/ubuntu/myfolder 
     state: directory 
  - name: i want to copy files 
    copy: 
      src: mystaticfile  
      dest: /home/ubuntu/mysataticfile.txt   
